version: '3'
services:
  server:
    image: flower_client
    environment:
      - server_ip=$server_ip
    command: python3 main_server.py comm.host=$server_ip
  
  client1:
    image: flower_client
    environment:
      - server_ip=$server_ip
    command: python3 client.py comm.host=$server_ip client.cid=0
  
  client2:
    image: flower_client
    environment:
      - server_ip=$server_ip
    command: python3 client.py comm.host=$server_ip client.cid=1

  