params : 
  num_classes : 10
  num_rounds : 5
  num_clients_per_round_fit : 10
  num_clients_per_round_eval : 10
  min_available_clients : 60
  fraction_fit : 0.1
  fraction_evaluate : 0.3
  wait_round : 5
  lr : 0.01
  num_groups : 16

# Mount Storage : "/srv/storage/energyfl@storage1.toulouse.grid5000.fr"
# /home/tunguyen/energyfl
data :
  data_name : CIFAR10 # (possible_value : CelebA, CIFAR10, CIFAR100, MNIST, FashionMNIST, TinyImageNet)
  partition_dir : /srv/storage/energyfl@storage1.toulouse.grid5000.fr/FLDATA/${data.data_name}/ParitionedData/${data.partition}/${data.num_clients}clients/alpha${data.alpha}
  batch_size : 50
  validation_split : 20
  num_clients : 100
  alpha : 0.1
  dataloaders : True # Load the dataset to dataloader object
  partition : label_skew # (possible_value : label_skew, iid, sample_skew)

client:
  lr : 0.001
  local_epochs : 3
  cid : 0
  dry_run : False
  decay_rate : 1 #decay=1 equal constant
  decay_steps : 1

comm :
  host : '[::]'
  port : 8080


defaults:
  - neuralnet : MobileNetV3Small
  - strategy : fedadam
  - optimizer : SGD
  - _self_ 

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}_${now:%H-%M-%S}/${hydra.job.name}_${client.cid}/
  
  

  