params : 
  num_classes : 10
  num_rounds : 5
  num_clients_per_round_fit : 2
  num_clients_per_round_eval : 2

data :
  data_name : CIFAR10 # (possible_value : CelebA, CIFAR10, CIFAR100, MNIST, FashionMNIST, TinyImageNet)
  data_dir : ${hydra:runtime.cwd}/data/${data.data_name}
  batch_size : 128
  validation_split : 10
  num_clients : 100
  alpha : 0.1
  partition : label_skew  # (possible_value : label_skew, iid, sample_skew)

client:
  lr : 0.1
  local_epochs : 5
  cid : 0
  dry_run : False
  decay_rate : 0.5 #decay=1 equal constant
  decay_steps : 10

comm :
  host : '[::]'
  port : 8080


defaults:
  - neuralnet : MobileNetV3Small
  - strategy : fedavg
  - optimizer : SGD
  - _self_ 

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}_${now:%H-%M-%S}/${hydra.job.name}_${client.cid}/
  
  

  