params : 
  num_classes : 10
  num_rounds : 3
  num_clients : 3
  batch_size : 128
  validation_split : 10
  num_clients_per_round_fit : 2
  num_clients_per_round_eval : 2
  fraction_fit : 1.0  
  fraction_evaluate: 1.0
  min_fit_clients : 2
  root_data : ${hydra:runtime.cwd}/data

client:
  lr : 0.01
  local_epochs : 1
  cid : 0
  dry_run : False
  decay_rate : 0.1
  decay_steps : 10

comm :
  host : 172.16.121.1
  port : 8080


defaults:
  - neuralnet : MobileNetV3Small
  - strategy : fedavg
  - optimizer : SGD
  - _self_ 

hydra:
  run:
    dir: ./outputs/${hydra.job.name}_${client.cid}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  

  