params : 
  num_classes : 10
  num_rounds : 10
  num_clients : 5
  batch_size : 64
  validation_split : 10
  num_clients_per_round_fit : 2
  num_clients_per_round_eval : 2
  root_data : ${hydra:runtime.cwd}/data

client:
  lr : 0.01
  local_epochs : 3
  lr_decay : 0.99
  cid : 0
  dry_run : False

comm :
  host : '[::]'
  port : 8080


defaults:
  - neuralnet : MobileNetV3
  - strategy : fedavg
  
  

  