params : 
  num_classes : 10
  num_rounds : 10
  num_clients : 2
  batch_size : 64
  validation_split : 10
  num_clients_per_round_fit : 2
  num_clients_per_round_eval : 2
  root_data : ${hydra:runtime.cwd}/data

client:
  lr : 0.001
  local_epochs : 3
  cid : 0
  dry_run : False

comm :
  host : 172.16.121.5
  port : 8080


defaults:
  - neuralnet : MobileNetV3Small
  - strategy : fedavg

hydra:
  run:
    dir: ./outputs/${hydra.job.name}_${client.cid}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  
  

  