params : 
  num_classes : 10
  num_rounds : 5
  num_clients : 2
  batch_size : 64
  validation_split : 10
  root_data : ${hydra:runtime.cwd}./data

client_params:
  lr : 0.01
  local_epochs : 3
  lr_decay : 0.99
  client_id : 1

comm:
  host : 192.168.1.110
  port : 8080