params : 
  num_classes : 10
  num_rounds : 10
  num_clients : 2
  batch_size : 64
  validation_split : 10
  root_data : ${hydra:runtime.cwd}/data

client:
  lr : 0.01
  local_epochs : 3
  lr_decay : 0.99
  cid : 1
  dry_run : False

comm:
  host : 172.16.36.3
  port : 8080