client_params:
  lr : 0.01
  local_epochs : 3
  lr_decay : 0.99
  num_classes : 10
  num_clients : 10
  batch_size : 64
  validation_split : 10
  root_data : ${hydra:runtime.cwd}/data

params :
  num_classes : 10
  num_rounds : 10
  #path_to_data : ${hydra:runtime.cwd}/data
  
comm :
  server_address : 192.168.1.110
  server_port : 8080



